# Generated by Django 3.1.4 on 2020-12-21 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_csvupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsform',
            name='country',
        ),
    ]
