# Generated by Django 2.2.17 on 2020-12-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TextField()),
                ('error_type', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
